default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bookstore
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>

production:
  <<: *default
  database: Bookstore_API_production
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>